server {
    listen 80;
    listen [::]:80;

    server_name taxdata.tk www.taxdata.tk;

    root /usr/share/nginx/html/taxdata;
    index index.html index.htm;

    client_max_body_size 10G;

    location / {
        proxy_pass http://localhost:3001;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
    } 
}
